# Generated by Django 4.1 on 2022-08-15 03:08

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_name", models.CharField(max_length=30)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Banca", "Banca"),
                            ("Red social", "Red social"),
                            ("Correo electrónico", "Correo electrónico"),
                            ("Otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_description", models.CharField(blank=True, max_length=50)),
                ("account_username", models.CharField(max_length=35)),
                (
                    "account_password",
                    django_cryptography.fields.encrypt(models.CharField(max_length=35)),
                ),
            ],
            options={"db_table": "accounts",},
        ),
    ]
